### ISSUE TITLE
Error loading page with dx.all.js

### ISSUE THREAD

**Issue by jtsom** [DevExpress/DevExtreme.AspNet.TagHelpers#45]
Any page with the DevExtreme javascript libraries included throw an exception, and no DevExpress controls will show / load.

The exception is:

```
dx.all.js:9 Uncaught TypeError: Cannot read property 'props' of undefined
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:165403
    at s (http://localhost:6796/lib/devextreme/js/dx.all.js:9:407)
    at Object.load (http://localhost:6796/lib/devextreme/js/dx.all.js:9:289)
    at Function.map (http://localhost:6796/lib/jquery/dist/jquery.js:457:13)
    at s (http://localhost:6796/lib/devextreme/js/dx.all.js:9:415)
    at Object.load (http://localhost:6796/lib/devextreme/js/dx.all.js:9:289)
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:188468
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:198372
```

The JS libraries loaded are:

```
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/globalize/lib/globalize.js"></script>
        <script src="~/lib/devextreme/js/dx.all.js"></script>
        <script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>
```

Version info:

```
    "bootstrap": "3.3.7",
    "jquery": "2.2.3",
    "jquery-validation": "1.14.0",
    "jquery-validation-unobtrusive": "3.2.6",
    "devextreme": "~15.2.11",
    "devextreme-aspnet-data": "~1.0.0"
```

Subsequently, trying to load a page with a DevExpress widget will all but lock up the browser and fail with multiple errors in the console:

```
<dx-data-grid column-auto-width="true">
    <datasource controller="Home" load-action="Load" />
    <column datafield="name" />
</dx-data-grid>
```

```
dx.all.js:9 Uncaught TypeError: Cannot read property 'props' of undefined(…)
jquery.js:3784 jQuery.Deferred exception: $(...).dxDataGrid is not a function TypeError: $(...).dxDataGrid is not a function
    at HTMLDocument.<anonymous> (http://localhost:6796/Home/About:46:43)
    at mightThrow (http://localhost:6796/lib/jquery/dist/jquery.js:3508:29)
    at process (http://localhost:6796/lib/jquery/dist/jquery.js:3576:12) undefinedjQuery.Deferred.exceptionHook @ jquery.js:3784
jquery.js:3793 Uncaught TypeError: $(...).dxDataGrid is not a function(…)
```

**Comment by AlekseyMartynov** [comment]
The issue may be caused by a current bug in VS Tooling for .NET Core, described at http://stackoverflow.com/q/37584520

Please check whether it's the case and try the solution from the mentioned Q&A thread.

**Comment by jtsom** [comment]
Yup. I've checked that. I also made sure my Jquery is set to version 3.1.0. But still get:

```
Uncaught TypeError: Cannot read property 'props' of undefined
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:165403
    at s (http://localhost:6796/lib/devextreme/js/dx.all.js:9:407)
    at Object.load (http://localhost:6796/lib/devextreme/js/dx.all.js:9:289)
    at Function.map (http://localhost:6796/lib/jquery/dist/jquery.js:457:13)
    at s (http://localhost:6796/lib/devextreme/js/dx.all.js:9:415)
    at Object.load (http://localhost:6796/lib/devextreme/js/dx.all.js:9:289)
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:188468
    at http://localhost:6796/lib/devextreme/js/dx.all.js:9:198372
```

The bower.json file is:
```
  "dependencies": {
    "bootstrap": "3.3.7",
    "jQuery": "3.1.0",
    "jquery-validation": "1.14.0",
    "jquery-validation-unobtrusive": "3.2.6",
    "devextreme": "~15.2.11",
    "devextreme-aspnet-data": "~1.0.0"
  }
```

The error is coming from this block of code in the dx.all.js file (the bit r.mouseHooks.props.concat(["pointerType", "pointerId", "pointers"]) ):

```
DevExpress.define("/ui/events/ui.events.eventRegistrator", ["jquery", "/utils/utils.memorizedCallbacks"], function(n, t) {
    var r = n.event, e = r.fixHooks, o = n.event.special, s = {
        props: r.mouseHooks.props.concat(["pointerType", "pointerId", "pointers"])
    }, i = new t, u = function(t, r) {
        var u = {};
        "noBubble"in r && (u.noBubble = r.noBubble),
        "bindType"in r && (u.bindType = r.bindType),
        "delegateType"in r && (u.delegateType = r.delegateType),
        n.each(["setup", "teardown", "add", "remove", "trigger", "handle", "_default", "dispose"], function(t, i) {
            r[i] && (u[i] = function() {
                var t = n.makeArray(arguments);
                return t.unshift(this),
                r[i].apply(r, t)
            }
            )
        }),
        e[t] = s,
        i.fire(t, u)
    }, f;
    return u.callbacks = i,
    f = function(n, t) {
        o[n] = t
    }
    ,
    i.add(f),
    u
}),
```

**Comment by San4es** [comment]
@jtsom DevExtreme does not support jQuery 3 for now. Use jQuery 2.0 - 2.1 (1.10 - 1.11 for IE8). See more information [here](http://js.devexpress.com/Documentation/Guide/Common/3rd-Party_Libraries_and_Frameworks_Integration/?version=15_2#3rd-Party_Libraries_and_Frameworks_Integration).
